### ISSUE TITLE
Strange right-click (long-press) options

### ISSUE THREAD

**Issue by Thyname** [snowhaze/SnowHaze-iOS#1]
When we long-press a link there's an option to add it to reading list but is there a reading list in snowhaze (I didn't find any)?
Also it would be nice to have a 'open in new tab' option, or do you have a reason for not having that?
Ipad2 iOS 9.3.5

**Comment by snowhaze** [comment]
Hi Thyname. The menu that pops up when long pressing a link is set by Apple. By their regulations, we are not allowed to make changes to this menu. Other apps do it but it is violating Apple's policies. So since we cannot change it the reading list appearing is the one from Safari. The link then gets added to the Safari reading list. 
Similar for the "Open in new Tab"; we can but are not allowed to change the menu and include this feature. Devices supporting 3D Touch, can open links in a new tab by Force Touch and the swipe up. I hope this clarifies how we handle these pre-set menus.

**Comment by Thyname** [comment]
Thank you for the clarification.
I'm actually in iOS 9 so it's good to have some privacy and ad blocking.
There's Brave browser, and it's good in this respect but it has trouble managing the lack of memory and thus crashes. Snowhaze works like Safari and reloads the tabs (and background tabs when they're opened), which is good.
Best regards.
